### ISSUE TITLE
百度OCR无法使用

### ISSUE THREAD

**Issue by Mr-wangwei** [godruoyi/ocr#10]
百度更换了授权方式 需要通过 https://aip.baidubce.com/oauth/2.0/token 获取 access_token 
![Uploading image.png…]()

**Comment by Mr-wangwei** [comment]
文档地址 https://ai.baidu.com/ai-doc/OCR/zk3h7xz52

**Comment by godruoyi** [comment]
有兴趣提个 PR 吗？不然我可能要晚些时候才能修复这个问题啦。

**Comment by godruoyi** [comment]
@Mr-wangwei 你现在可以再试试，使用 2.1 版本，有任何问题都可以给我提 Issues。
