### ISSUE TITLE
和Laravel 10 版本不兼容了

### ISSUE THREAD

**Issue by gyp719** [godruoyi/ocr#13]
和Laravel 10 版本不兼容了，--with-all-dependencie 也不行。

<img width="1464" alt="image" src="https://github.com/godruoyi/ocr/assets/30563368/1f139f9f-1e12-4ca8-8024-9557adf92234">

**Comment by godruoyi** [comment]
Thank you for pointing it out. I will fix it this week soon. If you are in a hurry, you can try to submitting a PR now. // 🐘

**Comment by gyp719** [comment]
> Thank you for pointing it out. I will fix it this week soon. If you are in a hurry, you can try to submitting a PR now. // 🐘

感谢大佬， 支持。

**Comment by gyp719** [comment]
更新到版本3了， 是否可以发布到 [packages](https://packagist.org/) 上

**Comment by godruoyi** [comment]
Actually, version 3.0 hasn't been released yet, I'm just changing the easy-container that OCR depends on, and with a bit of luck I'll update OCR to support PHP 8.1 this weekend.

**Comment by godruoyi** [comment]
Actually, version 3.0 hasn't been released yet, I'm just changing the easy-container that OCR depends on, and with a bit of luck I'll update OCR to support PHP 8.1 this weekend.

**Comment by gyp719** [comment]
> Actually, version 3.0 hasn't been released yet, I'm just changing the easy-container that OCR depends on, and with a bit of luck I'll update OCR to support PHP 8.1 this weekend.

so cool

**Comment by godruoyi** [comment]
Hi @gyp719, I have just released version 3.0 which requires a minimum PHP version of 8.1. Please try updating it and if you have any questions, feel free to post them in the issues section here. Have a great weekend!

**Comment by gyp719** [comment]
> Hi @gyp719, I have just released version 3.0 which requires a minimum PHP version of 8.1. Please try updating it and if you have any questions, feel free to post them in the issues section here. Have a great weekend!

好的， 一会试一试。感谢大佬🧍‍♂️

**Comment by gyp719** [comment]
使用 百度识别身份证 ， 按照文档， 提示 Class "Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory" not found


<img width="964" alt="image" src="https://github.com/godruoyi/ocr/assets/30563368/9d6bd159-52ec-4dd1-824e-3eab5994cd0e">

<img width="1354" alt="image" src="https://github.com/godruoyi/ocr/assets/30563368/8c108126-a8f0-44a0-8ca4-81fce1f2a3ed">

**Comment by gyp719** [comment]
是百度的除了身份证识别 ，其他的识别都支持吗

**Comment by gyp719** [comment]
> 使用 百度识别身份证 ， 按照文档， 提示 Class "Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory" not found
> 
> <img alt="image" width="964" src="https://user-images.githubusercontent.com/30563368/252002337-9d6bd159-52ec-4dd1-824e-3eab5994cd0e.png"> <img alt="image" width="1354" src="https://user-images.githubusercontent.com/30563368/252002523-8c108126-a8f0-44a0-8ca4-81fce1f2a3ed.png">

很抱歉， 是我的问题， 没有认真看文档， 可以正确调用， 在 vendor 目录中看到了
