### ISSUE TITLE
网络图片问题

### ISSUE THREAD

**Issue by mu0641** [godruoyi/ocr#4]
![image](https://user-images.githubusercontent.com/71642/38793272-2c737442-4183-11e8-9a87-e5fbf4d19d62.png)
如果提供网络链接的图片，没必要提示异常了，不是可以远程加载了吗？

**Comment by godruoyi** [comment]
由于 [百度 OCR](http://ai.baidu.com/tech/ocr) 部分接口不支持在线图片。

如 [通用文字识别](https://ai.baidu.com/docs#/OCR-API/e1bd77f3) 支持本地图片及在线图片
但 [行驶证识别等](https://ai.baidu.com/docs#/OCR-API/24158161) 不支持在线图片，所以这里用了

```php
FileConverter::toBase64Encode($images)
```
文件转换类去 `准备` 图片请求。确实，这是的判断是多余的，毕竟即使不是在线图片，也能 `download` 后再识别。

-----
最后感谢您使用 [ocr](https://github.com/godruoyi/ocr/) 这个项目，我会在下一个小版本修复这个问题，并在下一个 `release` 版本发布测试用例及几大服务商的新特性。
