### ISSUE TITLE
百度等有新接口了，如：手写文字识别，什么时候支持？

### ISSUE THREAD

**Issue by luffluo** [godruoyi/ocr#5]
如题

**Comment by godruoyi** [comment]
2.0 正在设计中，时间可能有点久，因为最近正在忙着结婚， 💃   💃   💃   💃

**Comment by basicbh** [comment]
结婚了吗god？
你的这个ocr怎么用呢，你官网倒是很不错

**Comment by godruoyi** [comment]
真是抱歉，拖了这么久，2.0 可算是发布了，哦耶！

```
composer require godruoyi/ocr:^2.0
```

具体文档参见 https://github.com/godruoyi/ocr/wiki/%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8

新版重新整理了目前服务商的接口，并且支持自定义。

```php
// 使用 laravel Facade 调用百度手写识别示列
OCR::baidu()->handwriting('https://images.godruoyi.com/images/comments/2020/11/14/bcb8e6d2bfcbf26b1abbafbfaa3601fe.jpg')->toArray()
```

![image](https://user-images.githubusercontent.com/16079222/99145849-03ce9500-26ad-11eb-9877-b37a0bdbcfa3.png)
