### ISSUE TITLE
Repeat background img

### ISSUE THREAD

**Issue by qiutian00** [godruoyi/ocr#9]
like this:
![image](https://user-images.githubusercontent.com/24382500/143725973-41e320b7-d47f-466f-a87c-2e7c717f9950.png)

add background-size: cover;
![image](https://user-images.githubusercontent.com/24382500/143726016-4f71eaee-661e-4848-998d-d1dfe22e687d.png)

**Comment by godruoyi** [comment]
That's great, thank thank thank you.
